"""
ReasoningEngine — Tahap 3: Analisis dan Validasi

Menerima EvidenceBundle + HypothesisResult dan merumuskan Root Cause.
tools=[] SELALU kosong — engine ini hanya menganalisis dan menyimpulkan.

Filosofi: "ReasoningEngine hanya membaca dan menyimpulkan. Ia tidak mencari."
"""

import json
from nexa.core.ai.providers.factory import ProviderFactory
from nexa.core.ai.knowledge.evidence import EvidenceBundle
from nexa.core.ai.cognitive.engines.hypothesis import HypothesisResult


class ReasoningResult:
    """Hasil analisis ReasoningEngine."""
    def __init__(self, root_cause: str, evidence_trail: list = None,
                 contradictions_found: bool = False, confidence: int = 0):
        self.root_cause = root_cause
        self.evidence_trail = evidence_trail or []
        self.contradictions_found = contradictions_found
        self.confidence = confidence


class ReasoningEngine:
    """
    Tahap 3: Menganalisis EvidenceBundle dan HypothesisResult.
    Merumuskan Root Cause dan rencana aksi yang tepat.
    tools=[] SELALU kosong.
    """

    def __init__(self):
        self.provider = ProviderFactory.create()

    def analyze(self, evidence_bundle: EvidenceBundle, user_goal: str,
                hypotheses: HypothesisResult = None) -> ReasoningResult:

        sys_prompt = (
            "You are the Nexa Reasoning Engine.\n"
            "You receive:\n"
            "  1. A User Goal\n"
            "  2. An Evidence Bundle (concrete findings from the codebase)\n"
            "  3. Hypotheses generated by the Hypothesis Engine\n\n"
            "Your task: deduce the precise Root Cause / Implementation Plan based on evidence.\n"
            "You MUST output STRICT JSON:\n"
            "{\n"
            "  \"root_cause\": \"string — precise, actionable analysis\",\n"
            "  \"evidence_trail\": [\"string — e.g. 'index.html line 315 has btn-warning'\"],\n"
            "  \"contradictions_found\": boolean,\n"
            "  \"confidence\": integer (0-100)\n"
            "}\n"
            "CRITICAL:\n"
            "1. If evidence clearly shows a specific file+line, cite it explicitly in evidence_trail.\n"
            "2. If evidence is insufficient (evidence_gaps exist), set confidence <= 40 and explain.\n"
            "3. ONLY output JSON. No explanations outside JSON."
        )

        evidence_text = evidence_bundle.to_context_text()
        hypotheses_text = hypotheses.summary_text() if hypotheses else "(no hypotheses)"

        prompt = (
            f"User Goal: {user_goal}\n\n"
            f"Hypotheses:\n{hypotheses_text}\n\n"
            f"{evidence_text}\n\n"
            "Please analyze and provide Root Cause."
        )

        messages = [
            {"role": "system", "content": sys_prompt},
            {"role": "user", "content": prompt}
        ]

        raw_resp = self.provider.generate(messages, tools=[])  # tools=[] — tidak boleh memanggil tool
        content = raw_resp.get("content", "") if isinstance(raw_resp, dict) else str(raw_resp)

        try:
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].strip()

            data = json.loads(content)
            return ReasoningResult(
                root_cause=data.get("root_cause", ""),
                evidence_trail=data.get("evidence_trail", []),
                contradictions_found=data.get("contradictions_found", False),
                confidence=data.get("confidence", 0)
            )
        except Exception as e:
            return ReasoningResult(
                root_cause=f"Reasoning failed: {e}\nRaw: {content[:300]}",
                evidence_trail=[],
                contradictions_found=False,
                confidence=0
            )
