<template>
  <div class="p-8">
    <div class="max-w-7xl mx-auto">
      <div class="text-center mb-12">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">Welcome to {{ app_name.capitalize() }}</h1>
        <p class="text-lg text-gray-600">Generated by Nexa Engine</p>
        <div class="mt-4">
          <a href="/admin" class="text-blue-600 hover:underline">Go to Admin</a>
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <!-- NEXA_NAV_LINKS -->
      </div>
    </div>
  </div>
</template>

<script setup>
// Home page for {{ app_name }}
</script>

